import pygame
import sys

# Initialize Pygame
pygame.init()

# Screen dimensions
WIDTH, HEIGHT = 600, 400
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Block Pushing Game")

# Colors
TAN = (210, 180, 140)
GRAY = (169, 169, 169)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)

# Game objects
player = pygame.Rect(50, 50, 40, 40)  # x, y, width, height
block = pygame.Rect(200, 150, 60, 60)
end_zone = pygame.Rect(500, 150, 80, 80)

# Movement speed
speed = 5

def move_player(keys):
    if keys[pygame.K_LEFT]:
        player.x -= speed
    if keys[pygame.K_RIGHT]:
        player.x += speed
    if keys[pygame.K_UP]:
        player.y -= speed
    if keys[pygame.K_DOWN]:
        player.y += speed

def check_collision():
    if player.colliderect(block):
        # Push the block in the same direction as the player
        if player.x < block.x:
            block.x += speed
        elif player.x > block.x:
            block.x -= speed
        if player.y < block.y:
            block.y += speed
        elif player.y > block.y:
            block.y -= speed

def game_won():
    return block.colliderect(end_zone)

# Game loop
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    # Player movement
    keys = pygame.key.get_pressed()
    move_player(keys)
    check_collision()

    # Check if the block is in the end zone
    if game_won():
        print("You won!")
        pygame.quit()
        sys.exit()

    # Drawing
    screen.fill(WHITE)  # Background color
    pygame.draw.rect(screen, BLUE, end_zone)  # End zone
    pygame.draw.rect(screen, GRAY, block)  # Block
    pygame.draw.rect(screen, TAN, player)  # Player

    # Refresh screen
    pygame.display.flip()
    pygame.time.Clock().tick(30)  # FPS limit
